name: Pull AppStack Changes

on:
  workflow_dispatch: {}

env:
  TF_STATE_BUCKET: "180217099948-states"
  APPSTACK_UUID: "b4320db7-9f52-4421-bdef-7c68437e2f81"
  AWS_ROLE_TO_ASSUME: "arn:aws:iam::180217099948:role/github"
  AWS_REGION: "us-west-2"

jobs:
  pull-appstack:
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download IaC
        uses: appcd-dev/download-action@v0.5
        env:
          APPCD_URL: https://cloud.stackgen.com
          APPCD_TOKEN: ${{ secrets.APPCD_TOKEN }}
        with:
          appstack_uuid: ${{ env.APPSTACK_UUID }}
          output: ./generated
          latest: true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Update IaC in PR
        uses: ./.github/workflows/update-iac-in-pr
        with:
          tf_state_bucket: ${{ env.TF_STATE_BUCKET }}
          tf_state_key: ${{ github.repository_owner }}/${{ github.repository }}/terraform.tfstate
          aws_region: ${{ env.AWS_REGION }}
